engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true

ratings:
  paths:
  - "**.py"